### ISSUE TITLE
Transition entre page

### ISSUE THREAD

**Issue by bastienald** [19h47/ledermannfilms#2]
Ralentir le masque (animation du bas vers le haut)
https://youtu.be/zfJkzUvJQGg

Je pense que ce serait pas mal que tu installes [Principle](https://principleformac.com/) en version d'essai pour avoir accès aux timings plus précisément. 
Fichier Principle : https://fromsmash.com/JL-Intro

**Comment by 19h47** [comment]
@nipson Je dois l'avoir quelque part, je m'en occupe
